name: Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=ver::$(node --version)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.node-version.outputs.ver }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache install
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-dep-${{ steps.node-version.outputs.ver }}-${{ hashFiles('**/package-lock.json') }}

      - run: yarn install

      - run: yarn lint
